services:
  mysql:
    container_name: 'mysql-magalu-technical-test'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_magalu_technical_test'
      - 'MYSQL_PASSWORD=GhostSthong567890@#'
      - 'MYSQL_ROOT_PASSWORD=GhostSthong567890@#'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'

# services:
#   postgres:
#     container_name: 'postgres-magalu-technical-test'
#     image: 'postgres:latest'
#     environment:
#       - 'POSTGRES_DB=db_magalu_technical_test'
#       - 'POSTGRES_PASSWORD=GhostSthong567890@#'
#       - 'POSTGRES_USER=admin'
#     ports:
#       - '5433:5432'
#    volumes:
#      - 'pgdata:/var/lib/postgresql/data'